on:
  workflow_dispatch:
    inputs:
      confirmDeploy:
        description: 'Confirm do a deployment?'
        required: true
        default: 'OK'

name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        ref: master

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: files.000webhost.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: public_html/
        timeout: 360000
